### ISSUE TITLE
Add travis test cases for websocket, elasticsearch, pagination etc

### ISSUE THREAD

**Issue by deepu105** [jhipster/jhipster-vuejs#126]
Add travis test cases for 
- websocket
- elasticsearch
- pagination
- Entity relationships (specially with Users)
- any other missing options

**Comment by pascalgrimaud** [comment]
@deepu105 : the bounty is not deserved for this ticket, because I already do all the work here https://github.com/jhipster/jhipster-vuejs/issues/2 and there was already a bounty. I suggest to remove it and keep it for another ticket.

But let's keep the ticket opened so we won't forget to add all these tests

**Comment by deepu105** [comment]
Ok @pascalgrimaud

**Comment by sahbi-ktifa** [comment]
As we already have maven, no-i18n, i18n, gradle, elasticsearch, pagination, entity relationships, protractor, gateway, session/jwt auth . I think we should only add websocket support on a new travis build.

**Comment by pascalgrimaud** [comment]
I will add this config when this https://github.com/jhipster/jhipster-vuejs/issues/116 will be fixed.
If we add it now, it will fail

**Comment by hdurix** [comment]
We can now add the WebSocket travis test.
@pascalgrimaud do you want me to have a look or do you want to do it?

**Comment by pascalgrimaud** [comment]
@hdurix : I can let you have a look so you'll know how it works. Don't hesitate to ping me if you have question

**Comment by sahbi-ktifa** [comment]
This is fixed with https://github.com/jhipster/jhipster-vuejs/pull/217.
