### ISSUE TITLE
Review component architecture

### ISSUE THREAD

**Issue by sahbi-ktifa** [jhipster/jhipster-vuejs#17]
- Use multiple files instead on single file component (styles, template, js)
- Stick to Angular/React directory tree

**Comment by atomfrede** [comment]
Why not use single file components?

**Comment by Gnuk** [comment]
I think it's a good idea to split il multiple files, we used it with @hdurix in our current project and we have an architecture like it:

* awesome-feature
    * AwesomeFeature.vue _It's the vue SFC file_
    * AwesomeFeature.component.ts _It's the TypeScript component file linked to the vue file_
    * AwesomeFeature.pug _In our context, we use pug as a template, it's the view file (in another context it will be AwesomeFeature.html)_
    * index.ts _It's the barrel file_

We have a lot of benefits with this architecture for unit tests (Jest), because we can import `vue` component with `component.ts` signatures easily and it looks like angular cli generated components/modules.

**Comment by sahbi-ktifa** [comment]
This issue was motivated after a discussion with @hdurix, he explained to me the benefits of using such architecture. You made it even clearer.

Furthermore, using this approach, we stay closed to the Angular organisation and so we'll help users not to be confused.

SFC approach is great but it can be very hard to maintain when coding huge components.

**Comment by atomfrede** [comment]
`SFC approach is great but it can be very hard to maintain when coding huge components.` We should not build huge components :)

**Comment by clarenced** [comment]
Hi, I want to work on issue #4  and I have questions regarding defining components in TS. 

According to the [documentation](https://vuejs.org/v2/guide/typescript.html#Basic-Usage), for typescript support, components must be define with `Vue.component` or `Vue.extend`. Otherwise, for a class based declaration, we can use the `vue-class-component` library that lets you define components in a class style with decorators, similar Angular. 

What is the recommended way of defining components with TS ?  What are the pros and cons of each method ? I want to work on this but I don't want to take a decision that is not approved by the community

**Comment by deepu105** [comment]
@clarenced I would prefer the `vue-class-component` way as its cleaner and is also officially maintained.
@sahbi-ktifa @hdurix @Gnuk WDYT?

**Comment by hdurix** [comment]
Yes exactly, `vue-class-component` will be very useful! @clarenced We've started a PR here: https://github.com/jhipster/jhipster-vuejs/pull/28, is that okay for you?

**Comment by deepu105** [comment]
@hdurix may be you can put the branch on this repo so that @clarenced can make PR against it. Else merge this PR and claim the bounty and create another ticket to convert templates to TS so that @clarenced can get the bounty for that

**Comment by clarenced** [comment]
Hi @hdurix did you able to merge your PR so I can start from here ?

**Comment by hdurix** [comment]
@clarenced you can start to add `vue-class-component` to `Register` component if you want.

**Comment by hdurix** [comment]
@atomfrede @deepu105 @sahbi-ktifa concerning the Single File Component, we propose to split the component Vue file and the component TypeScript file (see for instance the `Register` component: [Register.vue](https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/webapp/app/components/account/register/Register.vue) and [Register.component.ts](https://github.com/jhipster/jhipster-vuejs/blob/master/generators/client/templates/webapp/app/components/account/register/Register.component.ts)) for one main reason: testing with Jest having TypeScript types & signatures.

Here is an example of what we can do with Jest and TypeScript:
```ts
import { MyComponent } from '@/my-app';
import MyComponentClass from '@/my-app/my-component/MyComponent.component';
import { shallowMount, Wrapper } from '@vue/test-utils';

let wrapper: Wrapper<MyComponentClass>;
let myComponent: MyComponentClass;

describe('MyComponent', () => {
  beforeEach(() => {
    wrapper = shallowMount<MyComponentClass>(MyComponent);
    myComponent = wrapper.vm;
  });

  it('Is a Vue instance', () => {
    expect(wrapper.isVueInstance()).toBeTruthy();
  });

  it('Should value be undefined then defined', () => {
    expect(myComponent.value).toBeUndefined();
    expect(myComponent.defineValue());
    expect(myComponent.value).toBeDefined();
  });
});
```

In the above example, you can see that `MyComponent` has got a field `value` and a method `defineValue()`, both with available types in the test file, because it comes from the class `MyComponentClass`. I am not sure we could do the same with a complete Single File Component (Vue with HTML and TypeScript parts inside).

Does it seem good for you?

**Comment by deepu105** [comment]
Seems good to me

Thanks & Regards,
Deepu

**Comment by clarenced** [comment]
@hdurix Ok I will look at it

**Comment by sahbi-ktifa** [comment]
Looks good to me too!

**Comment by clarenced** [comment]
Guys, I have one issue. When I want to test the blueprint, I always get this message : 

```
Trying to use blueprint generator-jhipster-vuejs
     info No blueprint found for common falling back to default generator
Trying to use blueprint generator-jhipster-vuejs
     info No blueprint found for server falling back to default generator
```

Can we confirm that blueprint generator works ?
