### ISSUE TITLE
Upgrade to JHipster 6.6.X

### ISSUE THREAD

**Issue by donalmurtagh** [jhipster/jhipster-vuejs#526]
##### **Upgrade to JHipster 6.6.X**

The latest version of this blueprint (1.3.0) provides compatibility with JHipster 6.5.1, but it's not clear whether there are known issues with using v1.3.0 with the latest version of JHipster (currently 6.6.0).

If there are no known issues and/or the blueprint has been tested with JHipster 6.6.X, then it would be helpful to document this and/or upgrade the [sample app](https://github.com/jhipster/jhipster-sample-app-vuejs) to the latest JHipster version.

##### **Motivation for or Use Case**

I would like to use the latest version of JHipster, but it's unclear whether it's compatible with the latest version of this blueprint.

##### **Related issues or PR**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I just didn't have time to do the upgrade, as all the work is done during our personal time, it's not our day work...

Anyway, the only issue is the CI failed with OAuth2. If you can help to fix it, I can do a release with JHipster v6.6.0
Otherwise, you'll have to wait or use directly master branch.

**Comment by pascalgrimaud** [comment]
It's already done, so I'm closing this.
Then, I'm working on the compatibility with v6.7.0
