### ISSUE TITLE
Proper directory names in project's ReadMe file

### ISSUE THREAD

**Issue by JavaPantry** [jhipster/jhipster-vuejs#9]
Would you consider update `Running local Blueprint version for development` section in your doc and provide full path and correct folder names?

First two steps gives me same error

C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-vuejs>npm link
npm ERR! Link target resolves to the same directory as link source: C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-vuejs

**Comment by JavaPantry** [comment]
Also would be nice to outline absolutely required steps. (no 'if'-s or 'optional' scenarios )

**Comment by deepu105** [comment]
There are no absolute paths necessary, may be you are having issues since you are using it in windows. And from your error it looks like you are doing npm link from the `C:\Users\user\AppData\Roaming\npm\node_modules\generator-jhipster-vuejs` folder which is wrong.

Anyway i'll try to make it bit more cleaner
